arvada_dj/arvada_dj/urls.py
from django.contrib import admin
from django.contrib.auth.models import User
#from django.conf.urls import url, include
from django.urls import path, include
from rest_framework import routers, serializers, viewsets
#from comment.views import UserViewSet, GroupViewSet
import main
import map
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [

    path('main/', include('main.urls')),
    path('map/', include(('map.urls', 'map'), namespace='map')),
    path('', main.views.index),
    path('arvada_admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('arvada/', main.views.arvada),
    #path('', include(router.urls)),
    #path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('comment.urls')),
]

urlpatterns += staticfiles_urlpatterns()

arvada_dj/map/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='map_index'),
    path('super_map', views.super_map, name='super_map'),
]

arvada_dj/map/models.py
from django.db import models

# Create your models here.

arvada_dj/map/views.py
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    template = loader.get_template('map/map.html')
    context = {'super_map': 'false'}
    return HttpResponse(template.render(context, request))


@login_required
def super_map(request):
    template = loader.get_template('map/map.html')
    context = {'super_map': 'true'}
    return HttpResponse(template.render(context, request))

arvada_dj/map/templates/map/index2.html
{% extends "base_generic.html" %}

{% load static %}
{% block extra_head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <link rel="stylesheet" href="{% static 'webmap/./resources/ol.css' %}">
  <link rel="stylesheet" href="{% static 'webmap/resources/fontawesome-all.min.css' %}">
  <link rel="stylesheet" href="{% static 'webmap/./resources/ol3-layerswitcher.css' %}">
  <link rel="stylesheet" href="{% static 'webmap/./resources/qgis2web.css' %}">
  <link rel="stylesheet" href="{% static 'webmap/./resources/comments.css' %}">
  <style>
      .search-layer {
        top: 65px;
        left: .5em;
      }
      .ol-touch .search-layer {
        top: 80px;
      }
      </style>
      <style>
      html, body {
          background-color: #ffffff;
      }
      .ol-control button {
          background-color: #f8f8f8 !important;
          color: #000000 !important;
          border-radius: 0px !important;
      }
      .ol-zoom, .geolocate, .comment, .gcd-gl-control .ol-control {
          background-color: rgba(255,255,255,.4) !important;
          padding: 3px !important;
      }
      .ol-scale-line {
          background: none !important;
      }
      .ol-scale-line-inner {
          border: 2px solid #f8f8f8 !important;
          border-top: none !important;
          background: rgba(255, 255, 255, 0.5) !important;
          color: black !important;
      }
  </style>
  <style>
      html, body, #map {
          width: 100%;
          height: 100%;
          padding: 0;
          margin: 0;
          text-align: left;
          background: white;
      }
      .locate {
          top: 6em;
          left: .5em;
      }
      .comment {
        top: 9em;
        left: .5em;
      }
      #popup {
          width: 250px;
      }
  </style>
  <title> Arvada Stormwater Master Plan Web Map</title>
{% endblock %}

{% block content %}
  <div id="map">
      <div id="popup" class="ol-popup">
          <a href="#" id="popup-closer" class="ol-popup-closer"></a>
          <div id="popup-content"></div>
      </div>
  </div>
  <script src="{% static 'webmap/resources/qgis2web_expressions.js' %}"></script>
  <script src="{% static 'webmap/resources/polyfills.js' %}"></script>
  <script src="{% static 'webmap/./resources/functions.js' %}"></script>
  <script src="{% static 'webmap/./resources/ol.js' %}"></script>
  <script src="{% static 'webmap/./resources/ol3-layerswitcher.js' %}"></script>
  
  <script src="{% static 'webmap/styles/arvada_swmpcreeks_4_style.js' %}"></script>
  <script src="{% static 'webmap/styles/MajorWatersheds_0_style.js' %}"></script>
  <script src="{% static 'webmap/styles/ArvadaBoundary_0_style.js' %}"></script>

  <script src="{% static 'webmap/styles/MajorOutfallBasins_0_style.js' %}"></script>
  <script src="{% static 'webmap/styles/draft_Flow_Paths_0_style.js' %}"></script>
  <script src="{% static 'webmap/styles/arvada_designPoint_0_style.js' %}"></script>
  <script src="{% static 'webmap/styles/mp_picture.js' %}"></script>

  <script src="{% static 'webmap/styles/sw_inlet.js' %}"></script>
  <script src="{% static 'webmap/styles/sw_outfall_style.js' %}"></script>
  <script src="{% static 'webmap/styles/sw_gravity_main.js' %}"></script>
  <script src="{% static 'webmap/styles/sw_detention.js' %}"></script>
  <script src="{% static 'webmap/styles/sw_manhole.js' %}"></script>
  <script src="{% static 'webmap/styles/sw_pipe_out.js' %}"></script>
  <script src="{% static 'webmap/styles/sw_culvert.js' %}"></script>
  <script src="{% static 'webmap/styles/sw_storm_ditch.js' %}"></script>
  
  <script src="{% static 'webmap/styles/irr_gravity_main.js' %}"></script>
  <script src="{% static 'webmap/styles/irr_manhole_style.js' %}"></script>
  <script src="{% static 'webmap/styles/irr_ditch.js' %}"></script>
  
  <script src="{% static 'webmap/./layers/layers.js' %}" type="text/javascript"></script> 
  <script src="{% static 'webmap/./resources/qgis2web.js' %}"></script>
  <script src="{% static 'webmap/./resources/geolocate.js' %}"></script>
  <script src="{% static 'webmap/./resources/Autolinker.min.js' %}"></script>

  <script src="{% static 'webmap/./resources/comments.js' %}"></script>
  <script>
    var csrfToken = "{{csrf_token}}";
  </script>
{% endblock %}

arvada_dj/map/templates/map/map.html
{% extends "base_generic.html" %}

{% load static %}
{% block extra_head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <link rel="stylesheet" href="{% static 'webmap/resources/ol.css' %}?v{{ app_ver }}">
  <link rel="stylesheet" href="{% static 'webmap/resources/fontawesome-all.min.css' %}?v{{ app_ver }}">
  <link rel="stylesheet" href="{% static 'webmap/resources/ol3-layerswitcher.css' %}?v{{ app_ver }}">
  <link rel="stylesheet" href="{% static 'webmap/resources/qgis2web.css' %}?v{{ app_ver }}">
  <link rel="stylesheet" href="{% static 'webmap/resources/comments.css' %}?v{{ app_ver }}">
  <link rel="stylesheet" href="{% static 'webmap/resources/logos.css' %}?v{{ app_ver }}"> 

  <style>
      .search-layer {
        top: 65px;
        left: .5em;
      }
      .ol-touch .search-layer {
        top: 80px;
      }
      </style>
      <style>
      html, body {
          background-color: #ffffff;
      }
      .ol-control button {
          background-color: #f8f8f8 !important;
          color: #000000 !important;
          border-radius: 0px !important;
      }
      .ol-zoom, .geolocate, .comment, .gcd-gl-control .ol-control {
          background-color: rgba(255,255,255,.4) !important;
          padding: 3px !important;
      }
      .ol-scale-line {
          background: none !important;
      }
      .ol-scale-line-inner {
          border: 2px solid #f8f8f8 !important;
          border-top: none !important;
          background: rgba(255, 255, 255, 0.5) !important;
          color: black !important;
      }
  </style>

  <style>
      .locate {
          top: 6em;
          left: .5em;
      }
      .comment {
        top: 9em;
        left: .5em;
      }
      #popup {
          width: 250px;
      }
  </style>
  <title> Arvada Stormwater Master Plan Web Map</title>
{% endblock %}

{% block content %}
  <script>
    var csrfToken = "{{csrf_token}}";
    var userGroup = "{{user.groups.all.0.name}}";
    // Show closed comments, etc. in super map
    var superMap = {{super_map}};
  </script>

  <div id="map">
      <div id="popup" class="ol-popup">
          <a href="#" id="popup-closer" class="ol-popup-closer"></a>
          <div id="popup-content"></div>
      </div>
  </div>
  <div>
    <img class="arvada_logo" src="{% static 'webmap/styles/legend/arvada_logo.png' %}?v{{ app_ver }}">
    <img class="respec_logo" src="{% static 'webmap/styles/legend/respec_logo.png' %}?v{{ app_ver }}">
  </div>

  <script src="{% static 'webmap/resources/qgis2web_expressions.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/resources/polyfills.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/resources/functions.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/resources/ol.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/resources/ol3-layerswitcher.js' %}?v{{ app_ver }}"></script>
  
  <script src="{% static 'webmap/styles/arvada_swmpcreeks_4_style.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/MajorWatersheds_0_style.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/ArvadaBoundary_0_style.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/arvada_OutfallToCentroid_style.js' %}?v{{ app_ver }}"></script>

  <script src="{% static 'webmap/styles/MajorOutfallBasins_0_style.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/mp_subbasins.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/draft_Flow_Paths_0_style.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/arvada_designPoint_0_style.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/mp_picture.js' %}?v{{ app_ver }}"></script>

  <script src="{% static 'webmap/styles/sw_inlet.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/sw_outfall_style.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/sw_gravity_main.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/sw_detention.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/sw_manhole.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/sw_pipe_out.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/sw_culvert.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/sw_storm_ditch.js' %}?v{{ app_ver }}"></script>
  
  <script src="{% static 'webmap/styles/irr_gravity_main.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/irr_manhole_style.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/styles/irr_ditch.js' %}?v{{ app_ver }}"></script>
  
  <script src="{% static 'webmap/layers/layers.js' %}?v{{ app_ver }}"></script> 
  <script src="{% static 'webmap/resources/qgis2web.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/resources/geolocate.js' %}?v{{ app_ver }}"></script>
  <script src="{% static 'webmap/resources/Autolinker.min.js' %}?v{{ app_ver }}"></script>

  <script src="{% static 'webmap/resources/comments.js' %}?v{{ app_ver }}"></script>
  <script>
    // ------------------- Fix height of map 
    var setMapHeight = function () {
        var viewHeight = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
        var navHeight = document.getElementById('myTopnav').clientHeight;
        //alert("vieHeight "+ viewHeight+ " navheight "+ navHeight);
        document.getElementById("map").style.height = (viewHeight - navHeight)+"px";
        document.getElementById("content").style.height = (viewHeight - navHeight)+"px";
        map.updateSize(); // prevents map from being skewed on orientation change
    }
    setMapHeight();
    window.onresize = setMapHeight;

    // ------------------- Fix height of outer layer switcher to make visible panel
    if (! isMobileDevice()) {
      var myLayerSwitcher = document.getElementsByClassName('layer-switcher')[0];
      var myInnerLayerSwitcher = document.getElementsByClassName('panel')[0];
      myLayerSwitcher.style.height = myInnerLayerSwitcher.getBoundingClientRect().height + "px";
    }

    //----------------- Add link to super map for RESPEC users
    if (userGroup == "RESPEC") {
      let mapNavButton = document.getElementById('mapNavButton');
      let superMapButton = document.createElement('a');
      superMapButton.appendChild(document.createTextNode('Super-Map!!'));
      superMapButton.href = "{% url 'map:super_map'%}";
      mapNavButton.parentNode.insertBefore(superMapButton, mapNavButton.nextSibling);
    }
  </script>
{% endblock %}